name: test

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: kkrhdb
          POSTGRES_USER: viveknathani
          POSTGRES_PASSWORD: root
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0

    - name: build
      run: make build

    - name: test
      run: make test